import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useFirebase } from "../src/context/firebase.context";
import { httpsCallable } from "firebase/functions";

export default function Home() {
  const { functions } = useFirebase();
  const clickMe = async () => {
    const test = httpsCallable(functions, 'test');
    const result = await test({ name: 'steve' })
    console.log(result)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      home
      <button onClick={clickMe}>click</button>
    </div>
  )
}
